### ISSUE TITLE
Unable to use passport strategy twice

### ISSUE THREAD

**Issue by tobieeniafe** [themikenicholson/passport-jwt#150]
I'm trying to authenticate both users and admin using passport-jwt. I created two passport strategies, but for some reason, i get unauthorized on whichever strategy I add first to my file while the second one works. I tried separating them into files still no solution. is there a way around this? 
![screenshot 223](https://user-images.githubusercontent.com/18620774/36724824-a4b02eea-1bb4-11e8-8cef-f32dc15c7ce3.png)
![screenshot 221](https://user-images.githubusercontent.com/18620774/36724826-a8d7e526-1bb4-11e8-9800-83922b1cea27.png)
![screenshot 222](https://user-images.githubusercontent.com/18620774/36724828-ab23d4a2-1bb4-11e8-936c-ac49f9c58058.png)

**Comment by themikenicholson** [comment]
See the implementation of [passport.use()](https://github.com/jaredhanson/passport/blob/master/lib/authenticator.js#L51). You need to give each strategy a new name, otherwise, the default name ('jwt') is used and the last strategy passed to `passport.use()` overwrites the previous one. 

You should be able to do something like:

```
// for cleaner
passport.use('jwt-cleaner', new JwtStrategy(....));
...
// for customer
passport.use('jwt-customer', new JwtStrategy(...));
```

**Comment by themikenicholson** [comment]
Closing.  Feel free to re-opn if you can demonstrate an issue with this strategy.
