### ISSUE TITLE
Multi-tenanted application needs to defer the secretOrKey until after the token is retrieved

### ISSUE THREAD

**Issue by davesag** [themikenicholson/passport-jwt#37]
My application needs to be able to defer the use of the `secretOrKey` until after the `jwt` is unpacked as it's a multi-tenanted application where each issuer has been issued its own unique key.

In this case the `secretOrKey` option needs to be a function whose callback returns the correct secret or key, rather than it being a value.

This requires a small enhancement to `verify_jwt.js` which I'd be happy to do.

**Comment by themikenicholson** [comment]
Do you have examples of other strategies that work this way?  I was looking for examples and was unable to find any.

**Comment by themikenicholson** [comment]
Closing due due to no response from author.

**Comment by davesag** [comment]
Sorry I didn't realise you were waiting on a response from me. I am not sure of other impls but this PR solved our immediate problem.

I'm not on that project any more so do what you like. :-)

Dave

**Comment by manast** [comment]
Ok, maybe I have misunderstood how JWT token is supposed to work. But lets say that I have a REST API that I want to authenticate using JWT. I would expect that every user of the API has his own secret instead of sharing the same key to all the users... how do you solve this scenario when the *secretOrToken* is a fixed value?

**Comment by davesag** [comment]
@manast the secret in this case is something your service supplies to client services and apps, not to specific users.
