### ISSUE TITLE
jwt_payload.sub is undefined 

### ISSUE THREAD

**Issue by lnmunhoz** [themikenicholson/passport-jwt#68]
The `User.findOne(jwt_payload.sub)` is returning the first user always because the `sub` property is undefined.

This is the actual object that is coming from the `passport.use` callback.

```js
{ '$__':
   { strictMode: true,
     getters: {},
     wasPopulated: false,
     activePaths: { paths: [Object], states: [Object], stateNames: [Object] },
     emitter: { domain: null, _events: {}, _eventsCount: 0, _maxListeners: 0 } },
  isNew: false,
  _doc:
   { role: 'regular',
     __v: 0,
     password: '$2a$10$Q850U/ZpKf01DpQMN48vu.eltoQ6q9syACfy9EE/0WYl5gWYYzzSi',
     email: 'lucas@mail.com',
     _id: '5786f0419ec755449dac6551' },
  _pres:
   { '$__original_save': [ null, null, null ],
     '$__original_remove': [ null ] },
  _posts: { '$__original_save': [], '$__original_remove': [] },
  iat: 1468461125,
  exp: 1468547525 }
```

Using version `2.1.0`.
I am missing something or the docs are outdated?

**Comment by lnmunhoz** [comment]
Fixed using `jwt-simple` and changing the payload encode.

**Comment by PazzaVlad** [comment]
@lnmunhoz can you tell in more detail how you fix this problem?

I have a code:

`
module.exports = function(passport) {
  var opts = {};
  // Смотрим хедер и берез из него JWT токен
  opts.jwtFromRequest = ExtractJwt.fromAuthHeader();
  opts.secretOrKey = config.secret;

  passport.use(new JwtStrategy(opts, function (jwt_payload, done) {
    User.findOne({id:jwt_payload.sub}, function (err, user) {
      if (err) {
        return done(err, false);
      }
      if (user) {
        done(null, user);
      } else {
        done(null, false);
      }
    });
  }));
};
`

And it always find first user in mongodb. I solve this problem by using "_id:jwt_payload._doc._id" instead of  "id:jwt_payload.sub", but I suppose it's not good solution...
