### ISSUE TITLE
Dynamic secretOrKey

### ISSUE THREAD

**Issue by jakubzloczewski** [themikenicholson/passport-jwt#94]
Thanks for great library. I'm using it to validate jwt generated by openid connect identity provider. I would like to use different keys depend on 'kid' property in token signature. 

I think that good approach would be to have ability to provide getSecret function which will be called every verification.

What do you think?

**Comment by Freundschaft** [comment]
good call, ideally it would work with https://github.com/auth0/node-jwks-rsa

**Comment by Freundschaft** [comment]
added some rudimentary support (partially tested), please check out https://github.com/gfnork/passport-jwt/commit/203607948978635dba79c8b8fa02f0c2bc448936

**Comment by peacemakr** [comment]
@Freundschaft can your module solve https://github.com/themikenicholson/passport-jwt/issues/96

**Comment by themikenicholson** [comment]
Sorry, been busy this week. I'll sit down and look at this tomorrow night or Saturday.

**Comment by Freundschaft** [comment]
@peacemakr I'm not sure the two issues are related

**Comment by jondot** [comment]
@Freundschaft works well for me!

**Comment by themikenicholson** [comment]
So much for getting to this in January.  This is not the first request for a dynamic secretOrKey so its probably time to consider a new feature...

In your case it sounds like you need the JWT to be passed to the secretOrKey provider function. The other request has been multi-tenant applications which would probably need the whole request.  

Does a function like the following look sane?

```javascript
function secretOrKeyProvider(request, jwt) {
    var key = goFindTheKeySyn(...);
    return key;
};
```

Or would this need to include a callback to support async things like a DB access or async filesystem read or another api query like this:

```javascript
// result callback should have the signature result(err, key)
function secretOrKeyProvider(request, jwt, result) {
    Keys.findKey({id: jwt.kid}, function(err, key) {
       // actual implementation could just pass result callback, 
       // just done for clarity in example.
       result(null, key)
    });
};
```

Looking for feedback before I go off and implement something that doesn't work. Also accepting pull requests with implementation and tests!

**Comment by gpoole** [comment]
@themikenicholson I'm working with node-openid-client, which retrieves keys from a remote keystore via a JWKS URI on demand that I need to validate using passport-jwt, so I think that'd be a fairly common use case for this and a callback or Promise would be ideal.

Since I have this as a requirement, I can dedicate some time to it this week. Would you be willing to accept a PR along the lines of the second API you proposed? I'd prefer to return Promise, partly for convenience dealing with my other APIs but also because then you can allow a simple return value without people needing to be aware of the callback if they're not doing async. That said happy to go with your preference either way.

**Comment by themikenicholson** [comment]
@gpoole I'd prefer the callback for async so we don't introduce a new dependency to the library and because I'd like to follow the other passport strategies.  As far as I'm aware the primary passport strategies use callbacks.

I'd be happy to accept a pull request.  My only real stipulations are:
1.  Contributions are unit tested - currently code coverage is pretty high (~98%) and it lets me cut new releases with minimal testing and backwards compatibility with the   I should really write up a contributing guide at some point.
2. Backwards compatibility with simple strings for secretOrKey is maintained.

**Comment by themikenicholson** [comment]
Waiting on input on #108 before merging this and cutting a new release.

**Comment by adshastri** [comment]
Hi all, I'm relatively new to JWT authentication, but I've been reading about JWKs and JWKSs, and I also found this post (https://auth0.com/blog/navigating-rs256-and-jwks/) that explains it pretty well. As far as I understand, @Freundschaft's commit is simply adding support for a remote JWKS by using the 'kid' claim in the header to verify using the appropriate key. Would that be accurate?

I also had an idea I would like to run by people more knowledgeable than me, and, if possible, work on it as well as another passport strategy. I wasn't sure if this is the right place to do it, but it seems relevant. A JWKS, from what I have read, allows you to do key rotation when signing but the keys are still static, and losing the keys would still compromise your server(please correct me if that is inaccurate). Would it be feasible to randomly generate keys in the following way:

Start with a set of 10 random secret keys. Sign and verify as usual with a 'kid'. After a certain amount of time, say 1 minute, stop signing keys with the 1st key, but verify as usual with the 'kid'. Once all JWTs signed by the 1st key have expired, regenerate a new random key in that 1st spot. Now repeat the process, ad infinitum, for keys 2, 3, ... 10, back to 1. The keys can rarely be lost and once they are, they are useless after a certain amount of time.

**Comment by themikenicholson** [comment]
@adshastri I Appreciate your interest, however you're probably not going to get a lot of discussion in this github issue.  

I'm not super familiar with JWK but what you are proposing sounds like key rotation and i know for a fact that Google did this in some of their API's.  I'm not an OAuth guru but a few hits make it sound like it is done as part of that protocol as well.

**Comment by themikenicholson** [comment]
Finally got around to updating the docs and v3.0.0 is published on NPM. Big thanks to @gpoole for initial implementation and everyones patience as I've been a horrible maintainer the past few months and taken forever to get this new release out there.
